var express = require("express");
const { image } = require("../libs/multer");
const { imageKitUpload, imageKitList, imageKitDetail, imageKitDelete, imageKitEdit } = require("../controllers/media.controller");
var router = express.Router();
router.get("/images", imageKitList);
router.post("/images/upload", image.single("file"), imageKitUpload);
router.get("/images/:id", imageKitDetail);
router.put("/images/:id", imageKitEdit);
router.delete("/images/:id", imageKitDelete);
module.exports = router;
